### PR TITLE
Add rel="preload" option for JS/CSS

### PR DESCRIPTION
**Pull request by pglotov**
Added an option to specify css file with `rel="preload"`:
```
{% render_bundle 'commons' 'css' is_preload=True %}
```
It renders to
```
<link type="text/css" href="/static/dist/commons-ce3c39c62a45f3d1d496.bundle.css" rel="preload" as="style">
```

### CODE REVIEW

**Comment by EthanZeigler** [comment]
Is this exclusive to css? I have a lot of vue apps that would benefit massively from preloading

**Comment by Andruten** [comment]
@EthanZeigler I think it works with every kind of bundles.

**Comment by joaopslins** [comment]
Thanks for the PR! I've also added support for preloading scripted files.

The way I see it, this is the expected way of using this. Let me know if that makes sense:

https://github.com/django-webpack/django-webpack-loader/blob/075eba314ec44db42246abbdb0a36979c9135d83/tests/app/templates/preload.html#L1-L16

@rvlb I think this deserves a section in the README. Let me know if you are able to do it, or how I can help with this.

**Review by rvlb — APPROVED** [review]

**Comment by joaopslins** [comment]
FYI this was just included in the 1.3.0 version

**Pull request merged**
